---

dunst_home_directory: "{{ dunst_user_home }}" 
dunst_config_directory: "{{ dunst_home_directory }}/.config/dunst"

dunst_global_monitor: 0
dunst_global_follow: mouse
dunst_global_geometry: 1000x1000-30+20
dunst_global_indicate_hidden: "yes"
dunst_global_transparency: 0
dunst_global_padding: 12
dunst_global_horizontal_padding: 12
dunst_global_frame_width: 2
dunst_global_sort: "yes"
dunst_global_font: Monospace
dunst_global_font_size: 9
dunst_global_line_height: 1
dunst_global_browser: /usr/bin/firefox
dunst_global_corner_radius: 20

dunst_urgency_timeout: 10

...
