---

- name: Grepmam Environment
  hosts: localhost_group
  gather_facts: false

  tasks:

    - name: Import Fonts role...
      ansible.builtin.import_role:
        name: fonts
      tags: fonts

    - name: Import Picom role...
      ansible.builtin.import_role:
        name: picom
      tags: picom

    - name: Import Polybar role...
      ansible.builtin.import_role:
        name: polybar
      tags: polybar

    - name: Import Terminator role...
      ansible.builtin.import_role:
        name: terminator
      tags: terminator

    - name: Import Flameshot role...
      ansible.builtin.import_role:
        name: flameshot
      tags: flameshot

    - name: Import Rofi role...
      ansible.builtin.import_role:
        name: rofi
      tags: rofi

    - name: Import Feh role...
      ansible.builtin.import_role:
        name: feh
      tags: feh

    - name: Import i3 role...
      ansible.builtin.import_role:
        name: i3
      tags: i3

    - name: Import ZSH role...
      ansible.builtin.import_role:
        name: zsh
      tags: zsh

...
