---

- name: Install general tools...
  become: true
  community.general.pacman:
    name: "{{ item }}"
    state: present
  loop:
    - git
    - bat
    - htop
    - unzip
    - firefox
    - obsidian
    - keepassxc
    - curl
    - gcc
    - make
  tags: general_tools_install, install

...
