---

- name: Install general tools...
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - git
    - bat
    - htop
    - unzip
    - keepassxc
    - curl
    - gcc
    - make
    - mypaint
    - timeshift
    - arandr
    - gedit
  tags: general_tools_install, install

...
