---

- name: Install general tools on Arch Linux...
  become: true
  community.general.pacman:
    name: "{{ item }}"
    state: present
  loop:
    - bat
    - htop
    - unzip
    - firefox
    - obsidian
    - keepassxc 

...
