---

- name: Delete old settings directory
  ansible.builtin.file:
    state: absent
    path: "{{ picom_config_directory }}"

- name: Create Picom config directory...
  ansible.builtin.file:
    path: "{{ picom_config_directory }}"
    state: directory
    mode: 0755

- name: Configure Picom...
  ansible.builtin.template:
    src: templates/picom.conf.j2
    dest: "{{ picom_config_directory }}/picom.conf"
    mode: 0664

...
