---

- name: Import install.yml tasks...
  ansible.builtin.import_tasks: install.yml
  tags: picom_install

- name: Import configure.yml tasks... 
  ansible.builtin.import_tasks: configure.yml
  tags: picom_configure

...
