---

- name: Delete old settings directory
  ansible.builtin.file:
    state: absent
    path: "{{ i3_config_directory }}"

- name: Create i3 config directory...
  ansible.builtin.file:
    path: "{{ i3_subconfig_directory }}"
    state: directory
    mode: 0755

- name: Create subconfigs...
  ansible.builtin.template:
    src: templates/{{ item }}.conf.j2
    dest: "{{ i3_subconfig_directory }}/{{ item }}.conf"
    mode: 0664
  loop:
    - 01-keybindings
    - 02-window-rules
    - 03-apparence
    - 04-exec

- name: Create i3 config...
  ansible.builtin.template:
    src: templates/config.j2
    dest: "{{ i3_config_directory }}/config"
    mode: 0664

...
