---

- name: Delete old settings directory
  ansible.builtin.file:
    state: absent
    path: "{{ flameshot_config_directory }}"

- name: Create Flameshot directories...
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  loop:
    - "{{ flameshot_config_directory }}"
    - "{{ flameshot_save_directory }}"

- name: Configure flameshot...
  ansible.builtin.template:
    src: templates/flameshot.ini.j2
    dest: "{{ flameshot_config_directory }}/flameshot.ini"
    mode: 0664

...
