---

- name: Delete old settings directory
  ansible.builtin.file:
    state: absent
    path: "{{ flameshot_config_directory }}"

- name: Create Flameshot config directory...
  ansible.builtin.file:
    path: "{{ flameshot_config_directory }}"
    state: directory
    mode: 0755

- name: Create pictures directory...
  ansible.builtin.file:
    path: "{{ flameshot_pictures_directory }}"
    state: directory
    mode: 0755

- name: Create screenshots directory...
  ansible.builtin.file:
    path: "{{ flameshot_save_folder }}"
    state: directory
    mode: 0755

- name: Configure flameshot...
  ansible.builtin.template:
    src: templates/flameshot.ini.j2
    dest: "{{ flameshot_config_directory }}/flameshot.ini"
    mode: 0664

...
