---

- name: Delete old settings directory
  ansible.builtin.file:
    state: absent
    path: "{{ polybar_config_directory }}"

- name: Create Polybar config directory...
  ansible.builtin.file:
    path: "{{ polybar_config_directory }}"
    state: directory
    mode: 0755

- name: Create Polybar subconfig directory...
  ansible.builtin.file:
    path: "{{ polybar_subconfig_directory }}"
    state: directory
    mode: 0755

- name: Create subconfigs...
  ansible.builtin.template:
    src: templates/{{ item }}.ini.j2
    dest: "{{ polybar_subconfig_directory }}/{{ item }}.ini"
    mode: 0664
  loop:
    - colors
    - bars
    - modules
    - user_modules

- name: Create scripts directory...
  ansible.builtin.file:
    path: "{{ polybar_scripts_directory }}"
    state: directory
    mode: 0755

- name: Copy scripts to Polybar Scripts directory
  ansible.builtin.copy:
    src: scripts/dollar.sh
    dest: "{{ polybar_scripts_directory }}"
    mode: 0755

- name: Create Polybar config...
  ansible.builtin.template:
    src: templates/config.ini.j2
    dest: "{{ polybar_config_directory }}/config.ini"
    mode: 0664

- name: Copy launch.sh to Polybar directory
  ansible.builtin.copy:
    src: launch.sh
    dest: "{{ polybar_config_directory }}"
    mode: 0755

...
