---
# FALTA PROBAR

- name: Download WezTerm GPG key...
  ansible.builtin.get_url:
    url: https://apt.fury.io/wez/gpg.key
    dest: /tmp/wezterm.gpg
    mode: 0644

- name: Convert GPG key to keyring format...
  ansible.builtin.command: "gpg --yes --dearmor -o /etc/apt/keyrings/wezterm-fury.gpg /tmp/wezterm.gpg"
  creates: /etc/apt/keyrings/wezterm-fury.gpg

- name: Adding WezTerm repository to APT sources archive...
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list.d/wezterm.list
    line: 'deb [signed-by=/etc/apt/keyrings/wezterm-fury.gpg] https://apt.fury.io/wez/ * *'
    create: yes

- name: Clear GPG key temp file...
  ansible.builtin.file:
    path: /tmp/wezterm.gpg
    state: absent

- name: Update APT package index...
  ansible.builtin.apt:
    update_cache: yes

- name: Install Wezterm...
  become: true
  ansible.builtin.apt:
    name: wezterm
    state: present
  tags: terminator_install, install

...
