---

- name: Create Rofi config directory...
  ansible.builtin.file:
    path: "{{ rofi_directory }}"
    state: directory
    mode: 0755

- name: Configure Rofi...
  ansible.builtin.template:
    src: templates/config.rasi.j2
    dest: "{{ rofi_directory }}/config.rasi"
    mode: 0664

...
