---

- name: Include install tasks...
  ansible.builtin.include_tasks: "{{ ansible_os_family | lower }}_install.yml"
  tags: neofetch_install, install

- name: Import configure.yml tasks... 
  ansible.builtin.import_tasks: configure.yml
  tags: neofetch_configure, configure 

...
