---

- name: Create Nerd Fonts directory...
  ansible.builtin.file:
    path: "{{ fonts_directory }}/ttf/NerdFonts"
    state: directory
    mode: 0755

- name: Copy Nerd Fonts...
  ansible.builtin.copy:
    src: /tmp/nerd_fonts.zip
    dest: "{{ fonts_directory }}/ttf/NerdFonts"

- name: Extract Nerd Fonts...
  ansible.builtin.unarchive:
    src: "{{ fonts_directory }}/ttf/NerdFonts/nerd_fonts.zip"
    dest: "{{ fonts_directory }}/ttf/NerdFonts/"

- name: Update font cache...
  ansible.builtin.command: fc-cache -f -v

...
