---

- name: Download Font Awesome 6
  ansible.builtin.get_url:
    url: https://use.fontawesome.com/releases/v6.5.1/fontawesome-free-6.5.1-desktop.zip
    dest: /tmp/fontawesome.zip
  tags: fonts_install, install

- name: Download NerdFonts
  ansible.builtin.get_url:
    url: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.2/3270.zip 
    dest: /tmp/nerd_fonts.zip
  tags: fonts_install, install

...
